# Generated by Django 4.1.6 on 2023-02-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='q_stat',
            field=models.CharField(choices=[('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('AC', 'Accepted')], max_length=5, null=True),
        ),
    ]
