# Generated by Django 4.1.7 on 2023-03-12 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('q_title', models.CharField(max_length=40)),
                ('q_descrp', models.TextField()),
                ('q_ip_formate', models.TextField(blank=True, null=True)),
                ('q_op_formate', models.TextField(blank=True, null=True)),
                ('q_const', models.TextField(blank=True, null=True)),
                ('q_sip', models.TextField(blank=True, null=True)),
                ('q_sop', models.TextField(blank=True, null=True)),
                ('q_diff_level', models.CharField(max_length=50)),
                ('q_point', models.IntegerField(default=0)),
                ('q_aqrcy', models.IntegerField(default=0)),
                ('q_subns', models.IntegerField(default=0)),
                ('q_time_limit', models.IntegerField(default=1, null=True)),
                ('q_memory_limit', models.IntegerField(default=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(null=True)),
                ('t_ip', models.FileField(blank=True, upload_to='Question_Data/Uploaded')),
                ('t_op', models.FileField(blank=True, upload_to='Question_Data/Uploaded')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField(default=0)),
                ('team_attempted', models.IntegerField(default=0)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_testcases', models.TextField(blank=True, null=True)),
                ('s_code', models.TextField(blank=True, null=True)),
                ('s_pt', models.IntegerField(default=0)),
                ('s_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('q_status', models.CharField(blank=True, choices=[('TLE', 'Time Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('AC', 'Accepted')], max_length=5, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_login_number', models.IntegerField(default=0)),
                ('p_score', models.IntegerField(default=0)),
                ('p_is_started', models.BooleanField(default=False)),
                ('p_start_time', models.DateTimeField(blank=True, null=True)),
                ('p_is_junior', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
