# Generated by Django 4.1.7 on 2023-03-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='player_testcases',
        ),
    ]
