# Generated by Django 4.1.1 on 2023-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='q_status',
            field=models.CharField(blank=True, choices=[('TLE', 'Time Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('AC', 'Accepted')], max_length=5, null=True),
        ),
    ]
