# Generated by Django 4.1.7 on 2023-03-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_submission_player_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='s_language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
