# Generated by Django 4.1.7 on 2023-03-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_submission_s_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='p_is_loged_in',
            field=models.BooleanField(default=False),
        ),
    ]
