# Generated by Django 4.1.1 on 2023-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_player_p_is_loged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testcases',
            name='t_ip',
            field=models.FileField(blank=True, upload_to='Question_Data/Uploaded', verbose_name='Testcase Input'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='t_op',
            field=models.FileField(blank=True, upload_to='Question_Data/Uploaded', verbose_name='Testcase Output'),
        ),
    ]
