# Generated by Django 4.2 on 2023-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contest_time_alter_testcases_t_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isForJuniors',
            field=models.BooleanField(default=True),
        ),
    ]
