# Generated by Django 4.2 on 2023-05-06 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_question_questionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
