# Generated by Django 4.2 on 2023-05-06 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_team_teamtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
